version: '3.7'

services:
  vd-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: vd-server
    container_name: vd-server
    volumes:
      - ./server0xkid/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
