name: Deployment workflow
  
on:
  push: 
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          curl https://get.okteto.com -sSfL | sh
          okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
          
          okteto deploy --build
          
        
    
          
          
    
  
  
